services:
    frontend:
        build:
            context: ./frontend
        volumes:
            - ./frontend:/app
            - frontendModules:/app/node_modules
        ports:
            - "5173:5173"

    backend:
        build:
            context: ./backend
        volumes:
            - ./backend:/var/www
            - backendVendor:/var/www/vendor
        environment:
            APP_RP_ID: localhost
        ports:
            - "8080:80"

volumes:
    frontendModules:
    backendVendor:
